sass:
  style: compressed
permalink: :title
highlighter: rouge
markdown: kramdown
future: true
gems:
  - jekyll-feed
kramdown:
  input: GFM
  footnote_backlink: '&#8617;&#xfe0e;'
description: 'My experiences having an internship at Algolia!'
baseurl: /algolia-blog
